// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NGKAssignment3.Data;

namespace NGKAssignment3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201119104243_ThreeLatestWeatherData")]
    partial class ThreeLatestWeatherData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NGKAssignment3.Models.WeatherStation", b =>
                {
                    b.Property<long>("WeatherStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<float>("AirPressure")
                        .HasColumnType("real");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<int>("Lat")
                        .HasColumnType("int");

                    b.Property<int>("Lon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Temperatur")
                        .HasColumnType("real");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("WeatherStationId");

                    b.ToTable("Weatherstation");
                });
#pragma warning restore 612, 618
        }
    }
}
